import type { Metadata } from "next";
import { Geist, Geist_Mono ,Boldonse, Raleway } from "next/font/google";
import "./globals.css";
import ScrollContext from "@/components/ScrollContext";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const boldonse = Boldonse({
  variable: "--font-boldonse",
  subsets: ["latin"],
  weight: "400",
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TPA - Infera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${boldonse.variable} ${raleway.variable} antialiased`}
      >
        <ScrollContext>
        {children}
        </ScrollContext>
      </body>
    </html>
  );
}
